name: ghcr

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build release image
        run: docker build -t docker-deno:${GITHUB_REF/refs\/tags\//} - < Dockerfile

      - name: Authenticate to GitHub Container Registry
        run: |
          export CR_PAT=${{ secrets.CR_PAT }}
          echo $CR_PAT | docker login ghcr.io -u georgzepf --password-stdin

      - name: Tag release image
        run: docker tag docker-deno:${GITHUB_REF/refs\/tags\//} ghcr.io/georgzepf/docker-deno:${GITHUB_REF/refs\/tags\//}

      - name: Push release image to the GitHub Container Registry
        run: docker push ghcr.io/georgzepf/docker-deno:${GITHUB_REF/refs\/tags\//}
